### ISSUE TITLE
Project Check #7 Data Structures Algorithms Alex & Ethan

### ISSUE THREAD

**Issue by AlexKumar19** [AlexKumar19/fastpages-APCSP#30]
# Task: Working on AI bot:
- [x] completed making a simple frontend to work with
- [x] continued work on finding the private key
- [x] increased accuracy of response and made it so you can put multiple inputs 
- 3 hours each

![image](https://github.com/AlexKumar19/fastpages-APCSP/assets/110933283/c5befb37-40e0-4061-95a5-6be08bb77d39)
![image](https://github.com/AlexKumar19/fastpages-APCSP/assets/110933283/32353f79-3072-4558-953d-a417cd78cc07)
![image](https://github.com/AlexKumar19/fastpages-APCSP/assets/110933283/f813e2da-ed9a-4d36-b741-24f3814ca31f)

### future goals for AI bot:
- [ ]  complete the frontend to output response for ai API better
- [ ] Try to find potential ways to decrease time for API call
- [ ] possible create new key

# Task: creating community forum backend
- [x] create backend endpoints CRUD
- [ ] Create comments and name input
- [ ] READ old inputs from other users
- [ ] DELETE comments already made
- [ ] UPDATE your old comments
- [ ] SQL table properly working
- [ ] 6 hours

### Future goals for baclend
- [ ]  Ensure all endpoints are properly working
- [ ] add more functionality to the edit endpoint
- [ ] make the delete endpoint more specific
- [ ] possibly add UID

**Comment by realethantran** [comment]
- [x] [Python 2D Iteration and Animation Hacks](https://realethantran.github.io/fastpages_EthanT/1.d/2.b/3.b/c3.1/2023/05/16/DS-arrays_lab.html)
- [x] [Sorting Algorithms Hacks](https://github.com/realethantran/fastpages_EthanT/blob/master/_notebooks/2023-05-23-DS-sorting.ipynb)
